"""Every domain model, re-exported so importing this package populates the metadata.

Alembic imports this package; adding a model without listing it here leaves it
out of autogenerated migrations.
"""

from retailops_api.db.base import Base
from retailops_api.domain.models.category import Category
from retailops_api.domain.models.document import (
    DocumentFinding,
    DocumentStatus,
    DocumentType,
    FindingSeverity,
    SupplierDocument,
)
from retailops_api.domain.models.forecast_prediction import ForecastPrediction
from retailops_api.domain.models.forecast_run import ForecastRun
from retailops_api.domain.models.goods_receipt import (
    GoodsReceipt,
    GoodsReceiptLine,
    GoodsReceiptStatus,
)
from retailops_api.domain.models.job import JobKind, JobState, ProcessingJob
from retailops_api.domain.models.product import Product
from retailops_api.domain.models.purchase_order import (
    PurchaseOrder,
    PurchaseOrderLine,
    PurchaseOrderStatus,
)
from retailops_api.domain.models.reconciliation import (
    ExceptionResolution,
    ExceptionSeverity,
    ReconciliationException,
    ReconciliationRun,
)
from retailops_api.domain.models.review import (
    ReviewAISnapshot,
    ReviewAuditEvent,
    ReviewCase,
    ReviewDecision,
    ReviewDecisionRecord,
    ReviewEventType,
    ReviewPriority,
    ReviewStatus,
    ReviewSubjectType,
)
from retailops_api.domain.models.sales_record import SalesRecord
from retailops_api.domain.models.store import Store
from retailops_api.domain.models.supplier import Supplier
from retailops_api.domain.models.supplier_invoice import (
    SupplierInvoice,
    SupplierInvoiceLine,
    SupplierInvoiceStatus,
)
from retailops_api.domain.models.supplier_product import SupplierProduct

__all__ = [
    "Base",
    "Category",
    "DocumentFinding",
    "DocumentStatus",
    "DocumentType",
    "ExceptionResolution",
    "ExceptionSeverity",
    "FindingSeverity",
    "ForecastPrediction",
    "ForecastRun",
    "GoodsReceipt",
    "GoodsReceiptLine",
    "GoodsReceiptStatus",
    "JobKind",
    "JobState",
    "ProcessingJob",
    "Product",
    "PurchaseOrder",
    "PurchaseOrderLine",
    "PurchaseOrderStatus",
    "ReconciliationException",
    "ReconciliationRun",
    "ReviewAISnapshot",
    "ReviewAuditEvent",
    "ReviewCase",
    "ReviewDecision",
    "ReviewDecisionRecord",
    "ReviewEventType",
    "ReviewPriority",
    "ReviewStatus",
    "ReviewSubjectType",
    "SalesRecord",
    "Store",
    "Supplier",
    "SupplierDocument",
    "SupplierInvoice",
    "SupplierInvoiceLine",
    "SupplierInvoiceStatus",
    "SupplierProduct",
]
