"""Every domain model, re-exported so importing this package populates the metadata.

Alembic imports this package; adding a model without listing it here leaves it
out of autogenerated migrations.
"""

from retailops_api.db.base import Base
from retailops_api.domain.models.category import Category
from retailops_api.domain.models.product import Product
from retailops_api.domain.models.sales_record import SalesRecord
from retailops_api.domain.models.store import Store
from retailops_api.domain.models.supplier import Supplier
from retailops_api.domain.models.supplier_product import SupplierProduct

__all__ = [
    "Base",
    "Category",
    "Product",
    "SalesRecord",
    "Store",
    "Supplier",
    "SupplierProduct",
]
