import type {
  DocumentDetail,
  ForecastPage,
  ForecastRunDetail,
  Overview,
  ReviewDetail,
} from '@/lib/types';

export const overviewFixture: Overview = {
  generated_at: '2026-08-30T18:00:00+00:00',
  environment: 'local',
  forecasts: {
    run_count: 2,
    latest: {
      id: 1,
      model_id: 'naive',
      model_version: null,
      generated_at: '2026-08-30T13:32:00+00:00',
      cutoff: '2025-06-02',
      horizon: 4,
      problem_id: 'weekly_category_store_demand',
      status: 'evaluated',
      prediction_count: 2,
      metrics: { wape: 0.11, bias: 0.4, mae: 1, rmse: 1 },
    },
  },
  documents: { total: 3, awaiting_review: 1, parse_failed: 0 },
  reconciliation: {
    run_count: 1,
    open_exceptions: 2,
    error_exceptions: 1,
    total_financial_impact: '14.9000',
  },
  reviews: {
    open_cases: 4,
    decided_cases: 2,
    approved_cases: 1,
    rejected_cases: 1,
    corrected_cases: 0,
    cancelled_cases: 0,
    acceptance_rate: 0.5,
    rejection_rate: 0.5,
    correction_rate: 0,
    average_review_duration_seconds: 120,
    in_review: 1,
  },
};

export const forecastDetailFixture: ForecastRunDetail = {
  id: 1,
  model_id: 'naive',
  model_version: null,
  generated_at: '2026-08-30T13:32:00+00:00',
  cutoff: '2025-06-02',
  horizon: 2,
  problem_id: 'weekly_category_store_demand',
  status: 'evaluated',
  prediction_count: 2,
  metrics: { wape: 0.11, bias: 1, mae: 1, rmse: 1 },
  run_metadata: { overall_metrics: { wape: 0.11, bias: 1 } },
  predictions: [
    {
      store_code: 'ST-001',
      category_code: 'BEV-SOFT',
      period_start: '2025-06-09',
      step: 1,
      predicted: 10,
      actual: 9,
    },
    {
      store_code: 'ST-001',
      category_code: 'BEV-SOFT',
      period_start: '2025-06-16',
      step: 2,
      predicted: 11,
      actual: null,
    },
  ],
};

export const forecastPageFixture: ForecastPage = {
  items: [
    {
      id: forecastDetailFixture.id,
      model_id: forecastDetailFixture.model_id,
      model_version: forecastDetailFixture.model_version,
      generated_at: forecastDetailFixture.generated_at,
      cutoff: forecastDetailFixture.cutoff,
      horizon: forecastDetailFixture.horizon,
      problem_id: forecastDetailFixture.problem_id,
      status: forecastDetailFixture.status,
      prediction_count: forecastDetailFixture.prediction_count,
      metrics: forecastDetailFixture.metrics,
    },
  ],
  total: 1,
  limit: 50,
  offset: 0,
};

export const documentDetailFixture: DocumentDetail = {
  id: 9,
  supplier_id: 1,
  supplier_code: 'SUP-BEVCO',
  supplier_name: 'BevCo',
  filename: 'offer.csv',
  media_type: 'text/csv',
  status: 'review_ready',
  finding_count: 1,
  severity_summary: { error: 1, warning: 0, info: 0 },
  processed_at: '2026-08-30T17:00:00+00:00',
  created_at: '2026-08-30T17:00:00+00:00',
  checksum: 'ab'.repeat(32),
  storage_key: 'a'.repeat(32),
  document_type: 'supplier_sheet',
  findings: [
    {
      id: 3,
      code: 'required_field',
      field: 'description',
      row_reference: 2,
      severity: 'error',
      message: 'description is required',
      proposed_value: null,
      created_at: '2026-08-30T17:00:00+00:00',
      provenance: 'rule',
    },
  ],
  review_cases: [],
  rows: [
    {
      row_number: 2,
      supplier_sku: 'NW-SODA-330',
      ean: '7501999000011',
      description: 'New Cola 330ml',
      category: 'BEV-SOFT',
      cost: '6.5000',
      vat: '16',
      case_pack: 24,
      minimum_order_quantity: 1,
      lead_time_days: 5,
      invalid_fields: [],
      provenance: 'extracted',
    },
  ],
  rows_available: true,
};

export const reviewDetailFixture: ReviewDetail = {
  id: 12,
  subject_type: 'document_finding',
  document_finding_id: 3,
  reconciliation_exception_id: null,
  supplier_id: 1,
  supplier_code: 'SUP-BEVCO',
  supplier_name: 'BevCo',
  subject_summary: 'description is required',
  priority: 'medium',
  risk: 'high',
  confidence: '0.7200',
  financial_impact: '0.0000',
  recommended_action: 'human_review',
  status: 'in_review',
  reviewer: 'alice',
  opened_at: '2026-08-30T17:10:00+00:00',
  decided_at: null,
  created_at: '2026-08-30T17:00:00+00:00',
  updated_at: '2026-08-30T17:10:00+00:00',
  subject: {
    type: 'document_finding',
    finding: documentDetailFixture.findings[0]!,
    document: { id: 9, filename: 'offer.csv', status: 'review_ready' },
    exception: null,
  },
  snapshot: {
    id: 4,
    provider: 'mock',
    model: 'fixture',
    prompt_id: 'category_suggestion',
    prompt_version: '1',
    confidence: '0.7200',
    recommendation: 'human_review',
    input_hash: 'c'.repeat(64),
    reference_key: 'document_finding:3',
    original_output: {
      summary: 'La categoría parece bebidas.',
      reasoning_summary: 'El texto del proveedor no coincide con el catálogo.',
      suggested_value: 'BEV-SOFT',
    },
  },
  decision: null,
};
