"""Declarative base and the persistence conventions shared by every domain model.

Importing this module has no side effects beyond defining the metadata; the
models themselves are collected in ``retailops_api.domain.models`` so that both
Alembic and the application see an identical schema.
"""

from collections.abc import Mapping
from datetime import datetime
from decimal import Decimal
from typing import Any

from sqlalchemy import BigInteger, Boolean, DateTime, Integer, MetaData, Numeric, func, true
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy.types import TypeEngine

# Deterministic constraint names keep autogenerated migrations stable and let a
# downgrade drop a constraint by name without inspecting the live database.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

MONEY_PRECISION = 12
MONEY_SCALE = 4

#: Surrogate-key type. SQLite only auto-increments a column declared exactly as
#: ``INTEGER PRIMARY KEY``, so the variant keeps in-memory unit tests working.
IdType = BigInteger().with_variant(Integer, "sqlite")

#: Exact decimal type for every monetary amount. See ADR-002.
Money = Numeric(MONEY_PRECISION, MONEY_SCALE, asdecimal=True)

metadata = MetaData(naming_convention=NAMING_CONVENTION)

#: Maps a Python annotation to the column type it should produce, so a model can
#: write ``Mapped[Decimal]`` and get the agreed monetary type automatically.
TYPE_ANNOTATION_MAP: Mapping[Any, TypeEngine[Any]] = {
    datetime: DateTime(timezone=True),
    Decimal: Money,
    bool: Boolean(),
}


class Base(DeclarativeBase):
    """Declarative base for all RetailOps domain models."""

    metadata = metadata
    type_annotation_map = TYPE_ANNOTATION_MAP


# `sort_order` keeps mixin columns in a readable position: without it SQLAlchemy
# appends them after every column declared on the model itself.
_ID_ORDER = -100
_ACTIVE_ORDER = 90
_TIMESTAMP_ORDER = 100


class IdMixin:
    """Database-generated surrogate primary key."""

    id: Mapped[int] = mapped_column(
        IdType, primary_key=True, autoincrement=True, sort_order=_ID_ORDER
    )


class CreatedAtMixin:
    """Insert timestamp, generated by the database in UTC."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        sort_order=_TIMESTAMP_ORDER,
    )


class TimestampMixin(CreatedAtMixin):
    """Insert and last-modified timestamps for mutable records."""

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
        sort_order=_TIMESTAMP_ORDER + 1,
    )


class ActiveMixin:
    """Lifecycle flag used instead of deleting catalog rows."""

    active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        server_default=true(),
        default=True,
        sort_order=_ACTIVE_ORDER,
    )
