"""core retail domain

Creates the retail catalog and sales schema: categories, stores, suppliers,
products, supplier_products and sales_records. Tables are created parent-first
and dropped child-first because every foreign key is ON DELETE RESTRICT.

See docs/adr/ADR-002-core-retail-domain-model.md for the modelling decisions.

Revision ID: 024162a4b5f3
Revises: 6424a6340d6e
Create Date: 2026-08-30 11:13:37.632392

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "024162a4b5f3"
down_revision: str | None = "6424a6340d6e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("parent_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "parent_id IS NULL OR parent_id <> id", name=op.f("ck_categories_parent_not_self")
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
            name=op.f("fk_categories_parent_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("code", name=op.f("uq_categories_code")),
    )
    op.create_index(op.f("ix_categories_parent_id"), "categories", ["parent_id"], unique=False)
    op.create_table(
        "stores",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("region", sa.String(length=100), nullable=False),
        sa.Column("store_type", sa.String(length=50), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stores")),
        sa.UniqueConstraint("code", name=op.f("uq_stores_code")),
    )
    op.create_index(op.f("ix_stores_region"), "stores", ["region"], unique=False)
    op.create_index(op.f("ix_stores_store_type"), "stores", ["store_type"], unique=False)
    op.create_table(
        "suppliers",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("tax_id", sa.String(length=32), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suppliers")),
        sa.UniqueConstraint("code", name=op.f("uq_suppliers_code")),
    )
    op.create_table(
        "products",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("sku", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("ean", sa.String(length=14), nullable=True),
        sa.Column(
            "category_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_products_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("ean", name=op.f("uq_products_ean")),
        sa.UniqueConstraint("sku", name=op.f("uq_products_sku")),
    )
    op.create_index(op.f("ix_products_category_id"), "products", ["category_id"], unique=False)
    op.create_table(
        "sales_records",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("store_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "product_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("business_date", sa.Date(), nullable=False),
        sa.Column("units_sold", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column(
            "discount_amount",
            sa.Numeric(precision=12, scale=4),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("promotion", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("stock_on_hand", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "discount_amount >= 0", name=op.f("ck_sales_records_discount_amount_non_negative")
        ),
        sa.CheckConstraint(
            "stock_on_hand >= 0", name=op.f("ck_sales_records_stock_on_hand_non_negative")
        ),
        sa.CheckConstraint(
            "unit_price >= 0", name=op.f("ck_sales_records_unit_price_non_negative")
        ),
        sa.CheckConstraint(
            "units_sold >= 0", name=op.f("ck_sales_records_units_sold_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_sales_records_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_sales_records_store_id_stores"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_records")),
        sa.UniqueConstraint(
            "store_id",
            "product_id",
            "business_date",
            name=op.f("uq_sales_records_store_id_product_id_business_date"),
        ),
    )
    op.create_index(
        op.f("ix_sales_records_business_date"), "sales_records", ["business_date"], unique=False
    )
    op.create_index(
        op.f("ix_sales_records_product_id"), "sales_records", ["product_id"], unique=False
    )
    op.create_index(op.f("ix_sales_records_store_id"), "sales_records", ["store_id"], unique=False)
    op.create_table(
        "supplier_products",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "supplier_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "product_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("supplier_sku", sa.String(length=64), nullable=True),
        sa.Column("cost", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("case_pack", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "minimum_order_quantity", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("lead_time_days", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("case_pack > 0", name=op.f("ck_supplier_products_case_pack_positive")),
        sa.CheckConstraint("cost >= 0", name=op.f("ck_supplier_products_cost_non_negative")),
        sa.CheckConstraint(
            "lead_time_days >= 0", name=op.f("ck_supplier_products_lead_time_days_non_negative")
        ),
        sa.CheckConstraint(
            "minimum_order_quantity >= 0",
            name=op.f("ck_supplier_products_min_order_qty_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_supplier_products_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
            name=op.f("fk_supplier_products_supplier_id_suppliers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_supplier_products")),
        sa.UniqueConstraint(
            "supplier_id", "product_id", name=op.f("uq_supplier_products_supplier_id_product_id")
        ),
    )
    op.create_index(
        op.f("ix_supplier_products_product_id"), "supplier_products", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_supplier_products_supplier_id"), "supplier_products", ["supplier_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_supplier_products_supplier_id"), table_name="supplier_products")
    op.drop_index(op.f("ix_supplier_products_product_id"), table_name="supplier_products")
    op.drop_table("supplier_products")
    op.drop_index(op.f("ix_sales_records_store_id"), table_name="sales_records")
    op.drop_index(op.f("ix_sales_records_product_id"), table_name="sales_records")
    op.drop_index(op.f("ix_sales_records_business_date"), table_name="sales_records")
    op.drop_table("sales_records")
    op.drop_index(op.f("ix_products_category_id"), table_name="products")
    op.drop_table("products")
    op.drop_table("suppliers")
    op.drop_index(op.f("ix_stores_store_type"), table_name="stores")
    op.drop_index(op.f("ix_stores_region"), table_name="stores")
    op.drop_table("stores")
    op.drop_index(op.f("ix_categories_parent_id"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
